name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.203

    - name: Install dependencies
      run: dotnet restore

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Build Release
      run: dotnet build --configuration Release --no-restore

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore

    - name: Test
      run: coverlet TusLibros.UnitTests/bin/Debug/netcoreapp2.2/TusLibros.UnitTests.dll --target "dotnet" --targetargs "test TusLibros.UnitTests/TusLibros.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output coverage.xml

    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)